---
- name: Verify
  hosts: all
  tasks:
    - name: Check that traefik is deployed
      command: "docker service inspect traefik_traefik"
      changed_when: False

    - name: Check that example_app is deployed
      command: "docker service inspect example_app_helloworld"
      changed_when: False

    - name: Debug services
      command: "docker service ls"
      changed_when: False
      register: services
    - debug: var=services.stdout

    - name: Debug traefik
      command: "docker service ps traefik_traefik --no-trunc"
      changed_when: False
      register: traefik
    - debug: var=traefik.stdout

    - name: Debug consul
      command: "docker service ps traefik_traefik_consul --no-trunc"
      changed_when: False
      register: consul
    - debug: var=consul.stdout

    - name: Debug example_app
      command: "docker service ps example_app_helloworld --no-trunc"
      changed_when: False
      register: example_app
    - debug: var=example_app.stdout

    - name: Check that example_app is working
      command: 'curl -k -I --fail --silent -H "Host: yourcompany.com" https://localhost/'
      changed_when: False
      args:
        warn: False
      retries: 30
      delay: 10
      register: result
      until: result.rc == 0
